language: cpp
python: "3.7"
dist: bionic
sudo: require

#language: python

# see also: https://blog.travis-ci.com/support_for_go_c_and_cpp

# see also: https://docs.travis-ci.com/user/languages/cpp/

# see also: https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon

# see also: https://docs.conan.io/en/latest/integrations/ci/travisci.html

compiler:
  - clang
  - gcc

#env:
#  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#  - LINKER_FLAGS=""

services:
  - redis-server

before_install:
  - sudo apt-get install libboost-all-dev -y
  - sudo apt-get install python3 -y

install:
  # Install conan
  - pip install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
      - ubuntu-toolchain-r-test
    packages:
      - redis-tools
      - redis-server
      - gcc
      - g++
      - cmake

#don't do a shallow clone (for sonarqube)
git:
  depth: 9999999

script:
  - mkdir build || true
  - cd build
  - conan install ..
  - cd ../
  - chmod 755 build_travis.sh
  - ./build_travis.sh
  - cmake .
  - make

notifications:
  email: false