language: python
python: "3.7"
dist: bionic
sudo: require

#language: cpp

compiler:
  - clang
  - gcc

services:
  - redis-server

before_install:
  - sudo apt-get install libboost-all-dev python3 -y

install:
  # Install conan
  - pip install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.cache

addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
      - ubuntu-toolchain-r-test
    packages:
      - redis-tools
      - redis-server
      - gcc
      - g++
      - cmake

#don't do a shallow clone (for sonarqube)
git:
  depth: 9999999

script:
  - mkdir build
  - cd build
  - conan install ..
  - cd ../
  - chmod 755 build.sh
  - ./build.sh

notifications:
  email: false